version: "3.7"
services:

  configserver:
    image: morganlmd/adventureforge-configserver:latest
    container_name: "adventureforge-config-server-dev"
    ports:
      - "8888:8888"
    volumes:
      - ~/cloud-configuration/adventure-forge:/root/config
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=/root/config
    networks:
      backend:
        aliases:
          - "configserver"

  eurekaserver:
    image: morganlmd/adventureforge-eurekaserver:latest
    container_name: "adventureforge-eureka-server-dev"
    ports:
      - "8761:8761"
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://configserver:8888
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - database
      - configserver
    networks:
      backend:
        aliases:
          - "eurekaserver"

  gatewayserver:
    image: morganlmd/adventureforge-gatewayserver:latest
    container_name: "adventureforge-gateway-server-dev"
    ports:
      - "8890:8890"
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://configserver:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8761/eureka/
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - database
      - configserver
      - eurekaserver
    networks:
      backend:
        aliases:
          - "gateway"

  game-service:
    image: morganlmd/adventureforge-gameservice:latest
    container_name: "adventureforge-game-service-dev"
    ports:
      - "9001:9001"
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://configserver:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/adventureforgedb
      - SPRING_PROFILES_ACTIVE=dev
      - KEYCLOAK_AUTH_SERVER_URL=http://keycloak:8080/auth/
      - LOGGING_LEVEL_ROOT=WARN
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB=DEBUG
      - LOGGING_LEVEL_ORG_HIBERNATE=ERROR
    depends_on:
      - database
      - configserver
      - eurekaserver
    networks:
      - backend

  adventure-service:
    image: morganlmd/adventureforge-adventureservice:latest
    container_name: "adventureforge-adventure-service-dev"
    ports:
      - "9002:9002"
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://configserver:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/adventureforgedb
      - SPRING_PROFILES_ACTIVE=dev
      - KEYCLOAK_AUTH_SERVER_URL=http://keycloak:8080/auth/
      - LOGGING_LEVEL_ROOT=WARN
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB=DEBUG
      - LOGGING_LEVEL_ORG_HIBERNATE=ERROR
    depends_on:
      - database
      - configserver
      - eurekaserver
    networks:
      - backend

  database:
    image: "postgres:latest"
    container_name: "adventureforge-postgres-dev"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ../postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      backend:
        aliases:
          - "database"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  reactui:
    image: morganlmd/adventureforge-reactui
    container_name: "adventureforge-ui-dev"
    ports:
      - "3000:80"
    environment:
      - 'API_URL=http://gateway:8890'
      - 'KC_URL=http://keycloak:8080/auth'
      - 'KC_REALM=adventureforge-api'
      - 'KC_CLIENTID=adventureforge-ui'
    depends_on:
      - adventure-service
      - game-service
    networks:
      backend:
        aliases:
          - "ui"

  keycloak:
    image: jboss/keycloak
    container_name: "adventureforge-keycloak-dev"
    volumes:
      - ../keycloak:/opt/jboss/keycloak/imports
    environment:
      KEYCLOAK_IMPORT: /opt/jboss/keycloak/imports/realm-export.json -Dkeycloak.profile.feature.upload_scripts=enabled
      DB_VENDOR: POSTGRES
      DB_ADDR: database
      DB_DATABASE: adventureforgedb
      DB_USER: postgres
      DB_PASSWORD: postgres
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    depends_on:
      - database
    ports:
      - "8080:8080"
    networks:
      backend:
        aliases:
          - "keycloak"

networks:
  backend:
    driver: bridge