version: "3.8"
services:

  configserver:
    image: morganlmd/adventureforge-configserver:latest
    container_name: "config-server"
    ports:
      - "8888:8888"
    volumes:
      - ~/cloud-configuration/adventure-forge:/root/config
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=/root/config
    networks:
      backend:
        aliases:
          - "configserver"

  eurekaserver:
    image: morganlmd/adventureforge-eurekaserver:latest
    container_name: "eureka-server"
    ports:
      - "8761:8761"
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://configserver:8888
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      database:
        condition: service_healthy
      configserver:
        condition: service_started
    networks:
      backend:
        aliases:
          - "eurekaserver"

  gatewayserver:
    image: morganlmd/adventureforge-gatewayserver:latest
    container_name: "gateway-server"
    ports:
      - "8890:8890"
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://configserver:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8761/eureka/
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      database:
        condition: service_healthy
      configserver:
        condition: service_started
      eurekaserver:
        condition: service_started
    networks:
      backend:
        aliases:
          - "gateway"

  game-service:
    image: morganlmd/adventureforge-gameservice:latest
    container_name: "game-service"
    ports:
      - "9001:9001"
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://configserver:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/adventureforgedb
      - SPRING_PROFILES_ACTIVE=dev,testdata
      - LOGGING_LEVEL_ROOT=WARN
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB=DEBUG
      - LOGGING_LEVEL_ORG_HIBERNATE=ERROR
    depends_on:
      database:
        condition: service_healthy
      configserver:
        condition: service_started
      eurekaserver:
        condition: service_started
    networks:
      - backend

  adventure-service:
    image: morganlmd/adventureforge-adventureservice:latest
    container_name: "adventure-service"
    ports:
      - "9002:9002"
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://configserver:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/adventureforgedb
      - SPRING_PROFILES_ACTIVE=dev
      - LOGGING_LEVEL_ROOT=WARN
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB=DEBUG
      - LOGGING_LEVEL_ORG_HIBERNATE=ERROR
    depends_on:
      database:
        condition: service_healthy
      configserver:
        condition: service_started
      eurekaserver:
        condition: service_started
    networks:
      - backend

  database:
    image: "postgres:latest"
    container_name: "adventureforge-postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ../postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      backend:
        aliases:
          - "database"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  reactui:
    depends_on:
      adventure-service:
        condition: service_started
      game-service:
        condition: service_started
    image: morganlmd/adventureforge-reactui
    container_name: "adventureforge-ui"
    ports:
      - "3000:80"
    environment:
      - API_URI=http://gateway:8890
    networks:
      backend:
        aliases:
          - "ui"

networks:
  backend:
    driver: bridge