create table adventure
(
    adventure_id  integer generated by default as identity,
    date_created  timestamp,
    last_modified timestamp,
    user_created  varchar(255),
    user_modified varchar(255),
    uuid          binary,
    title         varchar(255),
    primary key (adventure_id)
);
create table adventure_appendice
(
    adventure_id integer not null,
    appendice_id integer not null,
    primary key (adventure_id, appendice_id)
);
create table appendice
(
    appendice_id  integer generated by default as identity,
    date_created  timestamp,
    last_modified timestamp,
    user_created  varchar(255),
    user_modified varchar(255),
    uuid          binary,
    title         varchar(255),
    primary key (appendice_id)
);
create table campaign
(
    campaign_id   integer generated by default as identity,
    date_created  timestamp,
    last_modified timestamp,
    user_created  varchar(255),
    user_modified varchar(255),
    uuid          binary,
    title         varchar(255),
    primary key (campaign_id)
);
create table campaign_adventure
(
    campaign_id  integer not null,
    adventure_id integer not null,
    primary key (campaign_id, adventure_id)
);
create table npc
(
    npc_id        integer generated by default as identity,
    date_created  timestamp,
    last_modified timestamp,
    user_created  varchar(255),
    user_modified varchar(255),
    uuid          binary,
    name          varchar(255),
    primary key (npc_id)
);
create table npc_adventure
(
    npc_id       integer not null,
    adventure_id integer not null,
    primary key (npc_id, adventure_id)
);
create table npc_scene
(
    npc_id   integer not null,
    scene_id integer not null,
    primary key (npc_id, scene_id)
);
create table place
(
    place_id      integer generated by default as identity,
    date_created  timestamp,
    last_modified timestamp,
    user_created  varchar(255),
    user_modified varchar(255),
    uuid          binary,
    name          varchar(255),
    primary key (place_id)
);
create table place_adventure
(
    place_id     integer not null,
    adventure_id integer not null,
    primary key (place_id, adventure_id)
);
create table place_scene
(
    place_id integer not null,
    scene_id integer not null,
    primary key (place_id, scene_id)
);
create table scene
(
    scene_id      integer generated by default as identity,
    date_created  timestamp,
    last_modified timestamp,
    user_created  varchar(255),
    user_modified varchar(255),
    uuid          binary,
    title         varchar(255),
    adventure_id  integer not null,
    primary key (scene_id)
);
create table scene_scene
(
    scene_a_id integer not null,
    scene_b_id integer not null,
    primary key (scene_a_id, scene_b_id)
);

alter table adventure_appendice
    add constraint FK8ok9ngejt9co1uwcicukjwoaa foreign key (appendice_id) references appendice;
alter table adventure_appendice
    add constraint FKq39kwwkgmf8dh48nb0wnqfuy0 foreign key (adventure_id) references adventure;
alter table campaign_adventure
    add constraint FKho2p6ipitvtspkjfqsq5bdrsy foreign key (adventure_id) references adventure;
alter table campaign_adventure
    add constraint FK2xfx0bpak8ml944gc7dwipn68 foreign key (campaign_id) references campaign;
alter table npc_adventure
    add constraint FKqm7bkoammvtilrplywkpko2rg foreign key (adventure_id) references adventure;
alter table npc_adventure
    add constraint FKbtivtvipx1b15ppeym69m2rxi foreign key (npc_id) references npc;
alter table npc_scene
    add constraint FKmovefkxinc7njmuglngxswvrg foreign key (scene_id) references scene;
alter table npc_scene
    add constraint FKr6xact9krbsacfuan644dk281 foreign key (npc_id) references npc;
alter table place_adventure
    add constraint FKlytgs3tenh47a04sr3fp8l8a foreign key (adventure_id) references adventure;
alter table place_adventure
    add constraint FKgik4euvvhehpevcilv3epyhx4 foreign key (place_id) references place;
alter table place_scene
    add constraint FKrk0dvgxnc495ynjm4n77c5rye foreign key (scene_id) references scene;
alter table place_scene
    add constraint FKthwgu4kxl6whsq0o762ogxyxx foreign key (place_id) references place;
alter table scene
    add constraint FK5sifhwrek2yvlvvaaeyjhigin foreign key (adventure_id) references adventure;
alter table scene_scene
    add constraint FK5qy8i7xs83bnesoy2k8bc8qmi foreign key (scene_b_id) references scene;
alter table scene_scene
    add constraint FK92nf84l95b0hqsg5rj26ibk61 foreign key (scene_a_id) references scene;
