version: "3.8"
services:

  configserver:
    image: morganlmd/adventureforge-configserver:latest
    container_name: "config-server"
    ports:
      - "8888:8888"
    volumes:
      - ~/cloud-configuration/adventure-forge:/root/config
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=/root/config
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      backend:
        aliases:
          - "configserver"

  eurekaserver:
    image: morganlmd/adventureforge-eurekaserver:latest
    container_name: "eureka-server"
    ports:
      - "8761:8761"
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://configserver:8888
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      configserver:
        condition: service_started
    networks:
      backend:
        aliases:
          - "eurekaserver"

  gatewayserver:
    image: morganlmd/adventureforge-gatewayserver:latest
    container_name: "gateway-server"
    ports:
      - "8890:8890"
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://configserver:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8761/eureka/
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      configserver:
        condition: service_started
      eurekaserver:
        condition: service_started
    networks:
      backend:
        aliases:
          - "gateway"

  game-service:
    image: morganlmd/adventureforge-gameservice:latest
    container_name: "game-service"
    ports:
      - "9001:9001"
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://configserver:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql:${DB_URL}/${DB_PORT}/${DB_NAME}
      - SPRING_PROFILES_ACTIVE=prod
      - KEYCLOAK_AUTH_SERVER_URL=${KC_URL}
      - LOGGING_LEVEL_ROOT=INFO
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB=INFO
      - LOGGING_LEVEL_ORG_HIBERNATE=INFO
      - DB_URL=${DB_URL}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - KC_URL=${KC_URL}
      - KC_SECRET=${KC_SECRET}
      - KC_REALM=${KC_REALM}
      - KC_RESOURCE=${KC_RESOURCE}
    depends_on:
      configserver:
        condition: service_started
      eurekaserver:
        condition: service_started
    networks:
      - backend

  adventure-service:
    image: morganlmd/adventureforge-adventureservice:latest
    container_name: "adventure-service"
    ports:
      - "9002:9002"
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://configserver:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql:${DB_ADDR}
      - SPRING_PROFILES_ACTIVE=prod
      - KEYCLOAK_AUTH_SERVER_URL=${KC_URL}
      - LOGGING_LEVEL_ROOT=INFO
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB=INFO
      - LOGGING_LEVEL_ORG_HIBERNATE=INFO
      - DB_URL=${DB_URL}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - KC_URL=${KC_URL}
      - KC_SECRET=${KC_SECRET}
      - KC_REALM=${KC_REALM}
      - KC_RESOURCE=${KC_RESOURCE}
    depends_on:
      configserver:
        condition: service_started
      eurekaserver:
        condition: service_started
    networks:
      - backend

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 config-server eureka-server gateway-server game-service adventure-service

networks:
  backend:
    driver: bridge