version: "3.7"
services:

  configserver:
    image: morganlmd/adventureforge-configserver:latest
    container_name: "adventureforge-config-server-prod"
    ports:
      - "8888:8888"
    volumes:
      - ~/cloud-configuration/adventure-forge:/root/config
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=/root/config
    networks:
      backend:
        aliases:
          - "configserver"

  eurekaserver:
    image: morganlmd/adventureforge-eurekaserver:latest
    container_name: "adventureforge-eureka-server-prod"
    ports:
      - "8761:8761"
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://configserver:8888
    depends_on:
      - configserver
    networks:
      backend:
        aliases:
          - "eurekaserver"

  gatewayserver:
    image: morganlmd/adventureforge-gatewayserver:latest
    container_name: "adventureforge-gateway-server-prod"
    ports:
      - "8890:8890"
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://configserver:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8761/eureka/
    depends_on:
      - configserver
      - eurekaserver
    networks:
      backend:
        aliases:
          - "gateway"

  game-service:
    image: morganlmd/adventureforge-gameservice:latest
    container_name: "adventureforge-game-service-prod"
    ports:
      - "9001:9001"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CLOUD_CONFIG_URI=http://configserver:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${DB_URL}:${DB_PORT}/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - KEYCLOAK_AUTH_SERVER_URL=${KC_URL}
      - KEYCLOAK_CREDENTIALS_SECRET=${KC_SECRET}
      - KEYCLOAK_REALM=${KC_REALM}
      - KEYCLOAK_RESOURCE=${KC_RESOURCE}
      - LOGGING_LEVEL_ROOT=INFO
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB=INFO
      - LOGGING_LEVEL_ORG_HIBERNATE=INFO
    depends_on:
      - configserver
      - eurekaserver
    networks:
      - backend

  adventure-service:
    image: morganlmd/adventureforge-adventureservice:latest
    container_name: "adventureforge-adventure-service-prod"
    ports:
      - "9002:9002"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CLOUD_CONFIG_URI=http://configserver:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${DB_URL}:${DB_PORT}/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - KEYCLOAK_AUTH_SERVER_URL=${KC_URL}
      - KEYCLOAK_CREDENTIALS_SECRET=${KC_SECRET}
      - KEYCLOAK_REALM=${KC_REALM}
      - KEYCLOAK_RESOURCE=${KC_RESOURCE}
      - LOGGING_LEVEL_ROOT=INFO
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB=INFO
      - LOGGING_LEVEL_ORG_HIBERNATE=INFO
    depends_on:
      - configserver
      - eurekaserver
    networks:
      - backend

networks:
  backend:
    driver: bridge