version: "3.8"
services:

  game-service:
    depends_on:
      - adventureforge-postgres
    image: "morganlmd/gameservice:0.0.1-SNAPSHOT"
    container_name: "game-service"
    ports:
      - 9001:9001
      - 8001:8001
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8001
      - SPRING_DATASOURCE_URL=jdbc:postgresql://adventuregame-postgres:5432/adventureforgedb_games
      - SPRING_PROFILES_ACTIVE=testdata
      #- LOGGING_LEVEL=DEBUG

  adventureforge-postgres:
    image: "postgres:14.1"
    container_name: "adventuregame-postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql