spring:
  application:
    name: game-service-dev
  datasource:
    url: jdbc:postgresql://localhost:5432/adventureforgedb
    username: postgres
    password: postgres
    hikari:
      connection-timeout: 2000 #ms
      maximum-pool-size: 5