server:
  port: 9002
  shutdown: graceful
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: game-service
  datasource:
    url: jdbc:postgresql://localhost:5432/adventureforgedb
    username: postgres
    password: postgres
    hikari:
      connection-timeout: 2000 #ms
      maximum-pool-size: 5
  jpa:
    database-platform:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
    show-sql: true
  jackson:
    default-property-inclusion: non_null

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8889/eureka/

info:
  system: Adventure Forge - game service

management:
  endpoints:
    web:
      exposure:
        include: configprops, env, flyway, health, heapdump, info, loggers, mappings
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

gameservice:
  testdata:
    enabled: true