server:
  port: 8890
  shutdown: graceful
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: gateway-server
  lifecycle:
    timeout-per-shutdown-phase: 15s
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      routes:
        - id: adventure-service
          uri: lb://adventure-service
          predicates:
            - Path=/adventures/**
          filters:
            - RewritePath=/adventures/(?<path>.*), /$\{path}
            - RemoveRequestHeader= Cookie,Set-Cookie
        - id: game-service
          uri: lb://game-service
          predicates:
            - Path=/games/**
          filters:
            - RewritePath=/games/(?<path>.*), /$\{path}
            - RemoveRequestHeader= Cookie,Set-Cookie

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8889/eureka/

info:
  system: Adventure Forge - gateway service

management:
  endpoints:
    web:
      exposure:
        include: configprops, env, flyway, health, heapdump, info, loggers, mappings
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

