spring:
  application:
    name: adventure-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      enabled: true # When using Config Service, set to true
      request-connect-timeout: 5000 # 5s
      request-read-timeout: 5000 # 5s
      fail-fast: false # In production, set to true
      retry:
        max-attempts: 6
        initial-interval: 1000 # 1s
        max-interval: 2000 # 2s
        multiplier: 1.1