server:
  port: 9001
  shutdown: graceful
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: game-service
  profiles:
    active: default
  datasource:
    url: jdbc:postgresql://localhost:5432/adventureforgedb_games
    username: postgres
    password: postgres
    hikari:
      connection-timeout: 2000 #ms
      maximum-pool-size: 5
  jpa:
    database-platform:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
    show-sql: true
  jackson:
    default-property-inclusion: non_null

gameservice:
  testdata:
    enabled: true